# Generated by Django 3.2.7 on 2021-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_profile_pic.jpeg', upload_to='avatars'),
        ),
    ]
